# Scratchpads config
# Format: name|key|command|icon|color(optional)
# Note: keybind changes require session restart, workspace/window rules apply immediately
# Lines starting with # are ignored
# Color is optional - omit for default white

music|Z|chromium --app=https://music.yandex.ru --profile-directory=Music|󰎆|
messenger|X|brave --app=https://messenger.360.yandex.com/ --profile-directory=Messenger|󰍡|#5ec4b6
telegram|V|telegram-desktop|󰍡|#54a0e0
obsidian|N|obsidian|󱓧|
