# Named workspaces config
# Format: name|key|command|icon|class_pattern|fullscreen(optional, true/false)
# Lines starting with # are ignored

IDE|I|pycharm|󱃖|jetbrains-.*|false
Steam|G|steam|󰓓|steam|false
